Repository kevin1024/vcrpy, pull requests merged in 2019-07, with the labels that each got.

#437 Minimal aiohttp streamreader support
  tests/integration/aiohttp_utils.py
  tests/integration/test_aiohttp.py
  vcr/stubs/aiohttp_stubs/__init__.py
Labels: enhancement

#408 FIX behaviour MockClientResponse.json() if body is empty
  tests/integration/aiohttp_utils.py
  tests/integration/test_aiohttp.py
  vcr/stubs/aiohttp_stubs/__init__.py
Labels: bug, need dev

#412 Record `json` kwarg in aiohttp request
  tests/integration/test_aiohttp.py
  vcr/stubs/aiohttp_stubs/__init__.py
Labels: need dev

#411 Fixes #382 boto3 compatibility.
  .travis.yml
  tests/fixtures/migration/new_cassette.yaml
  tests/integration/test_boto3.py
  tox.ini
  vcr/cassette.py
  vcr/patch.py
  vcr/request.py
  vcr/stubs/__init__.py
  vcr/stubs/boto3_stubs.py
Labels: bug, need review

#451 fix IndexError when empty cassette throws CannotOverwriteCassetteException
  .gitignore
  tox.ini
  vcr/cassette.py
Labels: bug
