Repository kevin1024/vcrpy, pull requests merged in 2023-07, with the labels that each got.

#735 Fix typo in docs
  docs/advanced.rst
Labels: bug, docs

#740 Fix query param filter for aiohttp (fixes #517)
  tests/integration/test_aiohttp.py
  tests/integration/test_filter.py
  vcr/stubs/aiohttp_stubs.py
Labels: bug

#739 Fix body matcher for chunked requests (fixes #734)
  tests/unit/test_matchers.py
  vcr/matchers.py
Labels: bug

#731 Drop boto 2 support
  docs/contributing.rst
  docs/installation.rst
  tests/integration/test_boto.py
  vcr/patch.py
  vcr/stubs/boto_stubs.py
Labels: enhancement
